let selectedSize = 4, sec = 600, listening = false, currentTopic = '', aiIndex = 0, timerId;
const names = [['Mannu', 'Dominator', 'Confident voice'], ['Tanisha', 'Data-driven', 'Calm voice'], ['Khushi', 'Quiet thinker', 'Soft voice'], ['Durgesh', 'Off-topic challenger', 'Energetic voice'], ['Arjun', 'Balanced analyst', 'Clear voice']];
const replies = [
  'AI will transform repetitive roles, but people who learn to work with AI can become more productive.',
  'I agree, but we should distinguish between job creation and whether displaced workers can actually transition into those jobs.',
  'One concern is that automation may affect entry-level positions first, so education and reskilling become important.',
  'Let us bring this back to the question: does creating new AI jobs compensate for the jobs being displaced?'
];
function show(id, btn) { document.querySelectorAll('.screen').forEach(x => x.classList.remove('active')); document.getElementById(id).classList.add('active'); if (btn) { document.querySelectorAll('.nav button').forEach(x => x.classList.remove('active')); btn.classList.add('active') } document.getElementById('title').textContent = id === 'setup' ? 'GD Arena' : id === 'live' ? 'Live Group Discussion' : id === 'report' ? 'Performance Report' : id === 'history' ? 'Progress' : 'About' }
document.querySelectorAll('#sizes .choice').forEach(b => b.onclick = () => { document.querySelectorAll('#sizes .choice').forEach(x => x.classList.remove('selected')); b.classList.add('selected'); selectedSize = +b.dataset.size });
function getSelected(id) { let x = document.querySelector('#' + id + ' .selected'); return x ? x.textContent : 'Normal' }
document.querySelectorAll('.choices:not(#sizes) .choice').forEach(b => b.onclick = () => { b.parentElement.querySelectorAll('.choice').forEach(x => x.classList.remove('selected')); b.classList.add('selected') });
function startGD() { currentTopic = document.getElementById('custom').value.trim() || document.getElementById('topic').value; document.getElementById('liveTopic').textContent = '“' + currentTopic + '”'; document.getElementById('reportTopic').textContent = '“' + currentTopic + '”'; document.getElementById('formatText').textContent = getSelected('formats'); document.getElementById('langText').textContent = getSelected('langs'); buildParticipants(); sec = 600; show('live'); clearInterval(timerId); timerId = setInterval(tick, 1000); toast('GD room created — AI participants are ready') }
function buildParticipants() { let box = document.getElementById('participants'); box.innerHTML = ''; for (let i = 0; i < selectedSize; i++) { let p = names[i]; let d = document.createElement('div'); d.className = 'person' + (i === 0 ? ' active' : ''); d.id = 'person' + i; d.innerHTML = '<b>' + p[0] + '</b><span class="dot"></span><div class="role">' + p[1] + '</div><div class="voice">🔊 ' + p[2] + '</div>'; box.appendChild(d) } }
function tick() { if (sec <= 0) { endGD(); return } sec--; let m = Math.floor(sec / 60), s = String(sec % 60).padStart(2, '0'); document.getElementById('timer').textContent = m + ':' + s; document.getElementById('timebar').style.width = (sec / 600 * 100) + '%'; if (sec === 420) document.getElementById('nudge').textContent = 'You have been quiet for 3 minutes — consider entering the discussion.' }
function add(who, text, me = false) { let p = document.createElement('p'); p.className = 'line' + (me ? ' me' : ''); p.innerHTML = '<b>' + who + ':</b> ' + text; let t = document.getElementById('transcript'); t.appendChild(p); t.scrollTop = t.scrollHeight }
function toggleMic() { listening = !listening; document.getElementById('mic').classList.toggle('live', listening); document.getElementById('speakBtn').textContent = listening ? 'Stop Speaking' : 'Start Speaking'; if (listening) { toast('Microphone active — speak now') } else { add('You', 'I believe AI will create new opportunities, especially for people who learn to work with AI tools.', true); document.getElementById('nudge').textContent = 'Good contribution. Try building on another participant next.'; setTimeout(nextAI, 500) } }
function nextAI() { let i = aiIndex % selectedSize; document.querySelectorAll('.person').forEach(x => x.classList.remove('active')); let el = document.getElementById('person' + i); if (el) el.classList.add('active'); add(names[i][0], replies[aiIndex % replies.length]); aiIndex++; let score = 78 + Math.floor(Math.random() * 8); document.getElementById('overall').innerHTML = score + '<span style="font-size:15px">/100</span>'; document.getElementById('m1').textContent = 80 + Math.floor(Math.random() * 8); document.getElementById('m2').textContent = 74 + Math.floor(Math.random() * 10) }
function endGD() { clearInterval(timerId); document.getElementById('finalScore').innerHTML = '84<span style="font-size:15px">/100</span>'; show('report'); toast('AI report generated from the GD transcript') }
function toast(t) { let x = document.getElementById('toast'); x.textContent = t; x.style.display = 'block'; setTimeout(() => x.style.display = 'none', 2200) }